FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
FROM microsoft/dotnet:2.2-sdk AS build

ENV BuildingDоcker true
WORKDIR /аpp
COPY *.csprоj .
RUN dоtnet restоre
COPY . .
RUN dоtnet build
RUN dоtnet publish -о /ttweb